CREATE TABLE member (
	u_id CHARACTER VARYING (12) NOT NULL,
	u_pw CHARACTER VARYING (20) NOT NULL,
	u_type INTEGER NOT NULL,
	u_email CHARACTER VARYING (30) NOT NULL,
	u_regdate DATE NOT NULL,
	CONSTRAINT pk_user PRIMARY KEY(u_id)
);
